CREATE TABLE Livros (
    ID INT PRIMARY KEY,
    Titulo VARCHAR(255),
    Autor VARCHAR(255),
    Genero VARCHAR(100),
    Preco DECIMAL(10, 2)
);


INSERT INTO Livros (ID, Titulo, Autor, Genero, Preco) VALUES
(1, '1984', 'George Orwell', 'Ficção Científica', 45.90),
(2, 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Fábula', 32.50),
(3, 'Dom Quixote', 'Miguel de Cervantes', 'Clássico', 89.90),
(4, 'Cem Anos de Solidão', 'Gabriel García Márquez', 'Realismo Mágico', 78.00),
(5, 'O Senhor dos Anéis', 'J.R.R. Tolkien', 'Fantasia', 135.00),
(6, 'Crime e Castigo', 'Fiódor Dostoiévski', 'Clássico', 65.50),
(7, 'O Grande Gatsby', 'F. Scott Fitzgerald', 'Clássico', 48.00),
(8, 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Fantasia', 55.90),
(9, 'A Revolução dos Bichos', 'George Orwell', 'Sátira', 38.00),
(10, 'A Menina que Roubava Livros', 'Markus Zusak', 'Drama', 69.90),
(11, 'O Código Da Vinci', 'Dan Brown', 'Suspense', 75.00),
(12, 'O Hobbit', 'J.R.R. Tolkien', 'Fantasia', 98.00),
(13, 'Orgulho e Preconceito', 'Jane Austen', 'Romance', 52.00),
(14, 'O Alquimista', 'Paulo Coelho', 'Autoajuda', 40.00),
(15, 'A Metamorfose', 'Franz Kafka', 'Ficção', 31.90),
(16, 'Drácula', 'Bram Stoker', 'Horror', 59.00),
(17, 'O Sol é Para Todos', 'Harper Lee', 'Ficção', 72.50),
(18, 'A Odisséia', 'Homero', 'Clássico', 110.00),
(19, 'Moby Dick', 'Herman Melville', 'Aventura', 88.00),
(20, 'O Retrato de Dorian Gray', 'Oscar Wilde', 'Clássico', 44.90),
(21, 'Frankenstein', 'Mary Shelley', 'Horror', 56.00),
(22, 'As Crônicas de Nárnia', 'C.S. Lewis', 'Fantasia', 145.00),
(23, 'Fahrenheit 451', 'Ray Bradbury', 'Ficção Científica', 62.00),
(24, 'O Morro dos Ventos Uivantes', 'Emily Brontë', 'Romance', 70.00),
(25, 'O Apanhador no Campo de Centeio', 'J.D. Salinger', 'Ficção', 61.50),
(26, 'O Estrangeiro', 'Albert Camus', 'Filosofia', 39.00),
(27, 'Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'Clássico', 43.00),
(28, 'O Processo', 'Franz Kafka', 'Ficção', 57.00),
(29, 'O Nome do Vento', 'Patrick Rothfuss', 'Fantasia', 99.00),
(30, 'As Vantagens de Ser Invisível', 'Stephen Chbosky', 'Romance', 50.00),
(31, 'Viagem ao Centro da Terra', 'Júlio Verne', 'Aventura', 68.00),
(32, 'Flores para Algernon', 'Daniel Keyes', 'Ficção Científica', 84.00),
(33, 'O Nome da Rosa', 'Umberto Eco', 'Suspense', 120.00),
(34, 'Guerra e Paz', 'Liev Tolstói', 'Clássico', 150.00),
(35, 'O Silêncio dos Inocentes', 'Thomas Harris', 'Suspense', 76.00),
(36, 'O Iluminado', 'Stephen King', 'Horror', 95.00),
(37, 'A Cabana', 'William P. Young', 'Ficção Cristã', 41.50),
(38, 'O Caçador de Pipas', 'Khaled Hosseini', 'Drama', 66.00),
(39, 'A Arte da Guerra', 'Sun Tzu', 'Estratégia', 33.00),
(40, 'Admirável Mundo Novo', 'Aldous Huxley', 'Ficção Científica', 54.00),
(41, 'A Cor Púrpura', 'Alice Walker', 'Ficção', 78.50),
(42, 'História de Duas Cidades', 'Charles Dickens', 'Clássico', 81.00),
(43, 'O Cemitério', 'Stephen King', 'Horror', 88.50),
(44, 'A Peste', 'Albert Camus', 'Filosofia', 49.00),
(45, 'O Ladrão de Raios', 'Rick Riordan', 'Fantasia', 67.00),
(46, 'O Guia do Mochileiro das Galáxias', 'Douglas Adams', 'Ficção Científica', 73.00),
(47, 'Kafka à Beira-Mar', 'Haruki Murakami', 'Realismo Mágico', 93.00),
(48, 'Um Estudo em Vermelho', 'Arthur Conan Doyle', 'Mistério', 46.00),
(49, 'Vinte Mil Léguas Submarinas', 'Júlio Verne', 'Aventura', 60.00),
(50, 'A Sombra do Vento', 'Carlos Ruiz Zafón', 'Suspense', 85.00),
(51, 'A Guerra dos Tronos', 'George R.R. Martin', 'Fantasia', 148.00),
(52, 'Duna', 'Frank Herbert', 'Ficção Científica', 130.00),
(53, 'O Médico e o Monstro', 'Robert Louis Stevenson', 'Clássico', 35.00),
(54, 'O Cântico de Aquiles', 'Madeline Miller', 'Mitologia', 82.00),
(55, 'A Garota no Trem', 'Paula Hawkins', 'Suspense', 64.00),
(56, 'O Símbolo Perdido', 'Dan Brown', 'Suspense', 79.00),
(57, 'A Culpa é das Estrelas', 'John Green', 'Romance', 41.00),
(58, 'A Fúria do Dragão', 'Raymond E. Feist', 'Fantasia', 105.00),
(59, 'O Castelo Animado', 'Diana Wynne Jones', 'Fantasia', 92.00),
(60, 'E o Vento Levou', 'Margaret Mitchell', 'Romance', 96.00),
(61, 'IT: A Coisa', 'Stephen King', 'Horror', 115.00),
(62, 'Neuromancer', 'William Gibson', 'Ficção Científica', 108.00),
(63, 'O Palácio de Inverno', 'John Boyne', 'História', 80.00),
(64, 'A Sétima Função da Linguagem', 'Laurent Binet', 'Mistério', 91.00),
(65, 'O Poder do Hábito', 'Charles Duhigg', 'Não Ficção', 77.00),
(66, 'Sapiens: Uma Breve História da Humanidade', 'Yuval Noah Harari', 'Não Ficção', 122.00),
(67, 'O Segredo de Brokeback Mountain', 'Annie Proulx', 'Romance', 47.00),
(68, 'A Rosa Branca', 'Hans Fallada', 'História', 63.00),
(69, 'O Sol da Meia-Noite', 'Stephenie Meyer', 'Romance', 118.00),
(70, 'O Diário de Anne Frank', 'Anne Frank', 'Biografia', 49.50),
(71, 'A Coroa de Gelo', 'Kristin Cashore', 'Fantasia', 83.00),
(72, 'O Monge e o Executivo', 'James C. Hunter', 'Negócios', 53.00),
(73, 'A Lista de Schindler', 'Thomas Keneally', 'História', 87.00),
(74, 'O Jardim das Borboletas', 'Dot Hutchinson', 'Suspense', 69.00),
(75, 'A Mulher na Janela', 'A.J. Finn', 'Suspense', 74.00),
(76, 'O Grito', 'Jostein Gaarder', 'Ficção', 58.00),
(77, 'Um Conto de Natal', 'Charles Dickens', 'Clássico', 36.00),
(78, 'O Mágico de Oz', 'L. Frank Baum', 'Fantasia', 42.00),
(79, 'A Dama das Camélias', 'Alexandre Dumas Filho', 'Romance', 51.00),
(80, 'O Exorcista', 'William Peter Blatty', 'Horror', 65.00),
(81, 'A Casa dos Espíritos', 'Isabel Allende', 'Realismo Mágico', 98.50),
(82, 'A Sombra e Ossos', 'Leigh Bardugo', 'Fantasia', 109.00),
(83, 'Cinderela Pop', 'Paula Pimenta', 'Romance', 55.00),
(84, 'O Retorno do Rei', 'J.R.R. Tolkien', 'Fantasia', 135.00),
(85, 'A Floresta dos Esquecidos', 'Kristin Hannah', 'Ficção', 76.50),
(86, 'Caim', 'José Saramago', 'Ficção', 68.50),
(87, 'Onde Cantam os Pássaros', 'Hannah Kent', 'História', 99.00),
(88, 'A Revolta de Atlas', 'Ayn Rand', 'Filosofia', 129.00),
(89, 'A Torre Negra', 'Stephen King', 'Fantasia', 147.00),
(90, 'O Guardião de Almas', 'Max Lucado', 'Ficção Cristã', 61.00),
(91, 'O Mundo de Sofia', 'Jostein Gaarder', 'Filosofia', 88.00),
(92, 'O Físico', 'Noah Gordon', 'História', 102.00),
(93, 'A Casa de Hades', 'Rick Riordan', 'Fantasia', 114.00),
(94, 'Vidas Secas', 'Graciliano Ramos', 'Clássico', 39.50),
(95, 'O Estranho Caso do Dr. Jekyll e Mr. Hyde', 'Robert Louis Stevenson', 'Clássico', 34.00),
(96, 'O Código de Hamurabi', 'Autor Desconhecido', 'História', 125.00),
(97, 'A Arte de Pensar Claramente', 'Rolf Dobelli', 'Não Ficção', 78.00),
(98, 'O Último Desejo', 'Andrzej Sapkowski', 'Fantasia', 106.00),
(99, 'A Vida Invisível de Addie LaRue', 'V.E. Schwab', 'Fantasia', 97.00),
(100, 'A Queda de um Anjo', 'Javier Sierra', 'Suspense', 85.00);