# Generated by Django 5.2.6 on 2025-09-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(help_text='Texto da pergunta enviada pelo usuário')),
                ('resposta', models.TextField(help_text='Resposta encontrada ou gerada pela IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
